### PR TITLE
Rename userScript.js to userScript.user.js

### PR DESCRIPTION
**Pull request by CosmicWebServices**

### CODE REVIEW

**Comment by JordanB-1337** [comment]
umm, why?

**Comment by CosmicWebServices** [comment]
So that when you click raw then the install popup will appear on tampemonkey

**Comment by JordanB-1337** [comment]
But now the link on scratch doesn't work kek

**Comment by CosmicWebServices** [comment]
Well herohamp has to change the link... it should have already been .user.js

**Pull request merged**
